service: serverless-esbuild-template

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x


functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    # Tweaks for SLS v9+
    # useInProcess: true
    # localEnvironment: true
  esbuild:
    minify: false
    bundle: true
    sourcemap: true
    target: node16
    packager: yarn
    watch:
      pattern: ['src/**/*.ts'] # match only typescript files in src directory
      ignore: ['.serverless/**/*', '.build', '.esbuild']

